### Many device configs have been moved to /etc/meshtasticd/available.d
### To activate, simply copy or link the appropriate file into /etc/meshtasticd/config.d

### Define your devices here using Broadcom pin numbering
### Uncomment the block that corresponds to your hardware
### Including the "Module:" line!
---

owner: LoRaHAM_Pi
ownerShort: LHPi

Lora:
  Module: RF95
  CS: 7
  IRQ: 16      # DIO0
  Reset: 6
#  DIO1: 12
#  DIO2: 20
#  DIO3: 21
  LED: 19      # Optional

# Optional: Interface aktivieren
Interfaces:
  CLI: true
  BLE: false
  MQTT: false 

